#!/bin/bash

exec 2>&1

# Prepare Drupal
cd {{pkg.path}}
drush -y site-install standard \
    --db-url="mysql://{{bind.database.first.cfg.username}}:{{bind.database.first.cfg.password}}@{{bind.database.first.sys.ip}}/{{cfg.drupal.db_name}}" \
    --site-name={{cfg.drupal.site_name}} \
    --account-name={{cfg.drupal.account_name}} \
    --account-pass={{cfg.drupal.account_password}}

# Copy the nginx config into position
cp -r {{pkg.svc_config_path}}/nginx.conf \
      {{pkgPathFor "core/nginx"}}/config/nginx.conf

# Copy the php-fom config into position
cp -n {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf.default \
      {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf

hab service load core/nginx --group {{svc.group}} --force
