#!/bin/bash

exec 2>&1

# Create the database
mysql -h {{bind.database.first.sys.ip}} \
      -u {{bind.database.first.cfg.username}} \
      -p {{bind.database.first.cfg.password}} \
      -e "create database IF NOT EXISTS {{cfg.db_name}}"

# Deploy Drupal
cd {{pkg.svc_data_path}}
{{pkg.path}}/vendor/drush/drush dl drupal --drupal-project-rename={{cfg.site_name}}
cd {{cfg.site_name}}
{{pkg.path}}/vendor/drush/drush site-install standard \
    --db-url='mysql://{{bind.database.first.cfg.username}}:{{bind.database.first.cfg.password}}@{{bind.database.first.sys.ip}}/{{cfg.db_name}}' \
    --site-name={{cfg.site_name}}
chmod +x {{pkg.svc_data_path}}
chown -R hab:hab {{pkg.svc_data_path}}

# Configure nginx
cp -r {{pkg.svc_config_path}}/nginx.conf \
      {{pkgPathFor "core/nginx"}}/config/nginx.conf

# Copy the php-fom config into position
cp -n {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf.default \
      {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf

hab service load core/nginx --group {{svc.group}} --force
